package com.photoproject.service.accounts.accounts;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
// import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/account") // This means URL's start with /account (after Application path)

public class AccountController {
    @Autowired // This means to get the bean called accountRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AccountRepository accountRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewAccount (@RequestParam String name,
            @RequestParam String sub,
            @RequestParam String email) {

        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Account n = new Account();
        n.setName(name);
        n.setSub(sub);
        n.setEmail(email);
        accountRepository.save(n);
        return "Saved";
    }
}
